/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author Maria Miluska
 */
public class Panel extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Panel() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton16 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();
        panelCartelera = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        peli = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        panelCompra = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel21 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        btnCartelera = new javax.swing.JLabel();
        panelAdministrador = new javax.swing.JPanel();

        jButton16.setText("jButton16");

        jLabel11.setText("jLabel11");

        jToggleButton6.setText("jToggleButton6");

        jToggleButton9.setText("jToggleButton9");

        jToggleButton10.setText("jToggleButton10");

        jLabel15.setText("jLabel15");

        jLabel16.setText("jLabel16");

        jLabel6.setText("Estreno:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(53, 55, 111));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_ticket_100px_2.png"))); // NOI18N
        Menu.add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 110, 70));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuario");
        Menu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 140, 40));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("AutoCine UTP");
        Menu.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 170, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_user_80px.png"))); // NOI18N
        Menu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 80));

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 110));

        panelPrincipal.setLayout(new java.awt.CardLayout());

        panelCartelera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Cartelera");
        panelCartelera.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 130, 20));
        panelCartelera.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 285, 800, -1));

        peli.setBackground(new java.awt.Color(255, 102, 102));
        peli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peliMouseClicked(evt);
            }
        });
        panelCartelera.add(peli, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 120, 140));

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));
        panelCartelera.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 110, 140));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        panelCartelera.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 110, 140));

        jLabel8.setText("Común:");
        panelCartelera.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jPanel4.setBackground(new java.awt.Color(102, 204, 0));
        panelCartelera.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 120, 140));

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        panelCartelera.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 120, 140));

        jPanel6.setBackground(new java.awt.Color(255, 153, 51));
        panelCartelera.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 120, 140));

        jPanel7.setBackground(new java.awt.Color(255, 51, 204));
        panelCartelera.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 120, 140));

        jPanel8.setBackground(new java.awt.Color(0, 255, 204));
        panelCartelera.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, 110, 140));

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));
        panelCartelera.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 110, 140));

        jPanel10.setBackground(new java.awt.Color(51, 0, 51));
        panelCartelera.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 100, 140));

        panelPrincipal.add(panelCartelera, "card2");

        panelCompra.setBackground(new java.awt.Color(255, 255, 255));
        panelCompra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(153, 204, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Chaos Walking");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabel12.setText("Descripcion.");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/chaos-250x300.png"))); // NOI18N
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, 310));

        panelCompra.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 600));

        jToggleButton1.setText("01");
        panelCompra.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jToggleButton2.setText("02");
        panelCompra.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, -1, -1));

        jToggleButton3.setText("03");
        panelCompra.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, -1, -1));

        jToggleButton4.setText("04");
        panelCompra.add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, -1, -1));

        jToggleButton5.setText("05");
        panelCompra.add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, -1, -1));

        jToggleButton7.setText("06");
        panelCompra.add(jToggleButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, -1, -1));

        jToggleButton8.setText("07");
        panelCompra.add(jToggleButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, -1, -1));

        jToggleButton11.setText("08");
        panelCompra.add(jToggleButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, -1, -1));

        jToggleButton12.setText("09");
        panelCompra.add(jToggleButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, -1, -1));

        jToggleButton13.setText("10");
        panelCompra.add(jToggleButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, -1, -1));

        jToggleButton14.setText("11");
        panelCompra.add(jToggleButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, -1));

        jToggleButton15.setText("12");
        panelCompra.add(jToggleButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, -1, -1));

        jToggleButton16.setText("13");
        panelCompra.add(jToggleButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, -1, -1));

        jToggleButton17.setText("14");
        panelCompra.add(jToggleButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, -1, -1));

        jToggleButton18.setText("15");
        panelCompra.add(jToggleButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, -1, -1));

        jToggleButton19.setText("16");
        panelCompra.add(jToggleButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, -1, -1));

        jToggleButton20.setText("17");
        panelCompra.add(jToggleButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, -1, -1));

        jToggleButton21.setText("18");
        panelCompra.add(jToggleButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("COMPRAR");
        panelCompra.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sala 1", "Sala 2" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        panelCompra.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 210, -1));

        jLabel14.setText("Elige sala:");
        panelCompra.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        jLabel17.setText("Elige numero de asiento:");
        panelCompra.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, -1));

        jCheckBox1.setText("3:00 - 4:15");
        panelCompra.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jLabel18.setText("Horario:");
        panelCompra.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jCheckBox2.setText("4:25 - 5:45");
        panelCompra.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        jCheckBox3.setText("5:55 - 7:10");
        panelCompra.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, -1));

        jCheckBox4.setText("7:20 - 8:45");
        panelCompra.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, -1));

        jCheckBox5.setText("8:55 - 10:10");
        panelCompra.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        jCheckBox6.setText("10:20 - 11:30");
        panelCompra.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, -1));

        jCheckBox7.setText("11:40 - 1:15");
        panelCompra.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Compra de boleto");
        panelCompra.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        jLabel20.setText("Selecciona día:");
        panelCompra.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        panelCompra.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 80, 160));

        jLabel21.setText("Seleccione cantidad:");
        panelCompra.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, -1, -1));
        panelCompra.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, -1, 30));

        btnCartelera.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCartelera.setText("Revisar Cartelera");
        btnCartelera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarteleraMouseClicked(evt);
            }
        });
        panelCompra.add(btnCartelera, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, -1, -1));

        panelPrincipal.add(panelCompra, "card3");

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 940, 600));

        panelAdministrador.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 940, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void peliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peliMouseClicked
        // TODO add your handling code here:
        if(evt.getSource()==peli)
        {
            panelCartelera.setVisible(false);
            panelCompra.setVisible(true);
        }
    }//GEN-LAST:event_peliMouseClicked

    private void btnCarteleraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarteleraMouseClicked
        // TODO add your handling code here:
        if(evt.getSource()==btnCartelera)
        {
            panelCartelera.setVisible(true);
            panelCompra.setVisible(false);
        }
    }//GEN-LAST:event_btnCarteleraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
      }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel btnCartelera;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JButton jButton16;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JPanel panelAdministrador;
    private javax.swing.JPanel panelCartelera;
    private javax.swing.JPanel panelCompra;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel peli;
    // End of variables declaration//GEN-END:variables
}
