/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author Maria Miluska
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jLabelTitulo = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JLabel();
        ttlNombre = new javax.swing.JLabel();
        Box1 = new javax.swing.JLabel();
        ttlApellidos = new javax.swing.JLabel();
        Box2 = new javax.swing.JLabel();
        ttlCorreo = new javax.swing.JLabel();
        Box3 = new javax.swing.JLabel();
        ttlContraseña = new javax.swing.JLabel();
        Box4 = new javax.swing.JLabel();
        btnCrearCuenta = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 130, 270, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 210, 270, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 290, 270, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 360, 270, -1));

        txtNombre.setBorder(null);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 110, 270, 20));

        txtApellidos.setBorder(null);
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 190, 270, 20));

        txtCorreo.setBorder(null);
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 270, 270, 20));

        jPassword.setBorder(null);
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 340, 270, 20));

        jLabelTitulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTitulo.setText("Registra tu cuenta");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 150, 20));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_go_back_48px.png"))); // NOI18N
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        ttlNombre.setForeground(new java.awt.Color(153, 153, 153));
        ttlNombre.setText("Nombre");
        getContentPane().add(ttlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 60, 20));

        Box1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/box-blue.png"))); // NOI18N
        getContentPane().add(Box1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 70));

        ttlApellidos.setForeground(new java.awt.Color(153, 153, 153));
        ttlApellidos.setText("Apellidos");
        getContentPane().add(ttlApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 70, 20));

        Box2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/box-blue.png"))); // NOI18N
        getContentPane().add(Box2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 70));

        ttlCorreo.setForeground(new java.awt.Color(153, 153, 153));
        ttlCorreo.setText("Correo");
        getContentPane().add(ttlCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 60, 20));

        Box3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/box-blue.png"))); // NOI18N
        getContentPane().add(Box3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 70));

        ttlContraseña.setForeground(new java.awt.Color(153, 153, 153));
        ttlContraseña.setText("Contraseña");
        getContentPane().add(ttlContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 80, 20));

        Box4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/box-blue.png"))); // NOI18N
        getContentPane().add(Box4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 70));

        btnCrearCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crearCuenta.png"))); // NOI18N
        getContentPane().add(btnCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, 60));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-blanco.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Box1;
    private javax.swing.JLabel Box2;
    private javax.swing.JLabel Box3;
    private javax.swing.JLabel Box4;
    private javax.swing.JLabel btnCrearCuenta;
    private javax.swing.JLabel btnRegresar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel ttlApellidos;
    private javax.swing.JLabel ttlContraseña;
    private javax.swing.JLabel ttlCorreo;
    private javax.swing.JLabel ttlNombre;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
